# Setup
title: "Weird Kitty"
description: "Weird Kitty's Website"
url: "https://weirdkittyz.github.io"   # This should NOT include the repo name
baseurl: "/ClancyGroup"                # This SHOULD include the repo name, starting with a slash
avatar: "/ClancyGroup/Pic/kitty.jpeg"
paginate: 10
permalink: pretty
cover_image: "/ClancyGroup/Pic/bg.jpeg"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll. This section is useful for files that are not meant to be served publicly
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: The Weird Kitty
  links: https://weirdkittyz.github.io/ClancyGroup/
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: The Weird Kitty
  url: weirdkittyz.github.io/
  email: ziy2@mcmaster.ca
