# Setup
title: "Weird Kitty Y &middot; Zi"
description: "Weird Kitty Y &middot; Zi's Website"
url: "https://weirdkittyz.github.io"
baseurl: "/ClancyGroup"
avatar: "/Pic/kitty.jpeg"
keywords: Pat Clancy, McMaster, condensed matter physics, Yijia Zi
paginate: 10
permalink: pretty
cover_image: "/Pic/bg.jpeg"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll. This section is useful for files that are not meant to be served publicly
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: The Weird Kitty
  links: https://weirdkittyz.github.io/ClancyGroup/
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: The Weird Kitty
  url: weirdkittyz.github.io/
  email: ziy2@mcmaster.ca

image_path: '{{ site.baseurl }}/Pic'
pdf_path: '{{ site.baseurl }}/PostFile'
